version: "3.7"
services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: complaints
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my-network

  text-classifier:
    build:
      context: ../zsc
    container_name: text-classifier
    ports:
      - "8000:3800"
    networks:
      - my-network

  my-app:
    build: .
    depends_on:
      - db
      - text-classifier
    networks:
      - my-network
    ports:
      - "4000:4000"
    environment:
      DB_NAME: complaints
      DB_DATABASE: postgres
      DB_HOST: db
      DB_PASSWORD: password
      DB_PORT: 5432
      PORT: 4000
      TEXT_CLASSIFICATION_SERVICE: "http://text-classifier:3800/classify"
    command: npm run start

volumes:
  db_data:

networks:
  my-network:
    driver: bridge