openapi: "3.0.0"
info:
  title: "Complaint Backend System"
  description: "Complaint API with AI-powered categorization"
  version: "1.0.0"

paths:
  /api/complaints/:
    get:
      summary: "Get all complaints"
      operationId: "getAllComplaints"
      tags:
        - Complaints
      responses:
        "200":
          description: "Success, returns all complaints in an array"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ComplaintDto"
        "500":
          description: "Internal server error"

    post:
      summary: "Create a new complaint"
      operationId: "createComplaint"
      tags:
        - Complaints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateComplaintDto"
      responses:
        "201":
          description: "Complaint created successfully"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComplaintDto"
        "400":
          description: "Invalid request payload"

  /api/complaints/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: "Complaint ID"
        schema:
          type: string

    get:
      summary: "Retrieve a complaint by ID"
      operationId: "getComplaintById"
      tags:
        - Complaints
      responses:
        "200":
          description: "Complaint successfully fetched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComplaintDto"
        "404":
          description: "Not Found"

    patch:
      summary: "Update complaint details"
      operationId: "updateComplaintById"
      tags:
        - Complaints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateComplaintDto"
      responses:
        "200":
          description: "Success, complaint updated"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ComplaintDto"
        "404":
          description: "Not Found"
        "500":
          description: "Internal server error"

    delete:
      summary: "Delete a complaint"
      operationId: "deleteComplaintById"
      tags:
        - Complaints
      responses:
        "204":
          description: "Complaint successfully deleted"
        "404":
          description: "Not Found"
        "500":
          description: "Internal server error"

components:
  schemas:
    ComplaintDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        category:
          type: string
          enum: ["billing", "service", "technical"]
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateComplaintDto:
      type: object
      required:
        - title
        - description
      properties:
        title:
          type: string
        description:
          type: string
