import { DataTypes, Model, Optional } from "sequelize";

// Define TypeScript interface for Complaint attributes
export interface ComplaintAttributes {
  id: string;
  title: string;
  description: string;
  category: "billing" | "service" | "technical";
  createdAt: Date;
  updatedAt: Date;
}

// Define attributes for new complaint creation (ID and timestamps generated by DB)
export interface ComplaintCreationAttributes
  extends Optional<ComplaintAttributes, "id" | "createdAt" | "updatedAt"> {}

// Define Sequelize Model with the correct types
export class ComplaintModel
  extends Model<ComplaintAttributes, ComplaintCreationAttributes>
  implements ComplaintAttributes
{
  public id!: string;
  public title!: string;
  public description!: string;
  public category!: "billing" | "service" | "technical";
  public createdAt!: Date;
  public updatedAt!: Date;
}