import { DataTypes, Model, Optional } from "sequelize";
import { sequelize } from "../config/db";

/**
 * @openapi
 * components:
 *  schemas:
 *    CreateComplaintsDto:
 *      type: object
 *      properties:
 *        title:
 *          type: string
 *          default: Stuck at loading page
 *        description:
 *          type: text
 *          default: My applicaiton would not load to anywhere and stuck at the home page
 *      required:
 *        - title
 *        - description
 * 
 *    UpdateComplaintDto:
 *      type: object
 *      properties:
 *        title:
 *          type: string
 *          default: Stuck at loading page
 *        description:
 *          type: text
 *          default: My applicaiton would not load to anywhere and stuck at the home page
 *      required:
 * 
 *    ComplaintDto:
 *      type: object
 *      properties:
 *        id:
 *          type: string
 *        title:
 *          type: string
 *        description:
 *          type: string
 *        category:
 *          type: enum("billing", "service", "technical")
 *        createdAt:
 *          type: string
 *          format: date
 *        updatedAt:
 *          type: string
 *          format: date
 */

// Define TypeScript interface for Complaint attributes
export interface ComplaintAttributes {
  id: string;
  title: string;
  description: string;
  category: "billing" | "service" | "technical";
  createdAt: Date;
  updatedAt: Date;
}

// Define attributes for new complaint creation (ID and timestamps generated by DB)
export interface ComplaintCreationAttributes
  extends Optional<ComplaintAttributes, "id" | "createdAt" | "updatedAt"> {}

// Define Sequelize Model with the correct types
export class ComplaintModel
  extends Model<ComplaintAttributes, ComplaintCreationAttributes>
  implements ComplaintAttributes
{
  public id!: string;
  public title!: string;
  public description!: string;
  public category!: "billing" | "service" | "technical";
  public createdAt!: Date;
  public updatedAt!: Date;
}

// Initialize model
ComplaintModel.init(
  {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true,
    },
    title: {
      type: DataTypes.STRING,
      allowNull: false,
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: false,
    },
    category: {
      type: DataTypes.ENUM("billing", "service", "technical"),
      allowNull: false,
    },
    createdAt: {
        type: DataTypes.DATE,
        allowNull: false,
    },
    updatedAt: {
        type: DataTypes.DATE,
        allowNull: false,
    },
  },
  {
    sequelize,
    tableName: "complaints",
    timestamps: true,
  }
);

export default ComplaintModel;
